# Generated by Django 5.0.1 on 2024-02-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='businessexpense',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='businessexpense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businessexpense',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_expense',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='company',
            name='income',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='propertie',
        ),
        migrations.RemoveField(
            model_name='company',
            name='property_expense',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
        migrations.DeleteModel(
            name='BusinessExpense',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
