# Generated by Django 5.0.1 on 2024-02-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0002_remove_businessexpense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
    ]
