# Generated by Django 5.0.1 on 2024-02-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0003_alter_category_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='mile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mile',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='mile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
